import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PogOwl
 */
public class ViewStatus extends javax.swing.JFrame {

    /**
     * Creates new form ViewStatus
     */
    Object selectedValue = null;
    public ViewStatus() {
        initComponents();
        tbReport.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){
                if (!e.getValueIsAdjusting() && tbReport.getSelectedRow() != -1){
                    selectedValue = tbReport.getValueAt(tbReport.getSelectedRow(), 0);
                }
            }
        });
    }
    Functions fnc = new Functions();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReport = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("View Status");

        tbReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbReport);

        btnShow.setText("View Report Detail");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnShow)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.setVisible(false);
        new ManagerOption().setVisible(true);
    }                                        

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        try {
            String relativePath = "Report.txt"; // Replace with actual relative path if different
            String filePath = fnc.getFileLocation(relativePath);
            String line;
            String[] columnsName = {"ReportID","Date","Status"};
            Functions.UneditableTableModel model = new Functions.UneditableTableModel(columnsName, 0);
            tbReport.setModel(model);
            model.setColumnIdentifiers(columnsName);

            //Specialized file readings
            try(BufferedReader br = new BufferedReader(new FileReader(filePath))){
                
                br.readLine(); //this is used to skip the header
                while ((line = br.readLine()) != null){
                    String[] parts = line.split(" @ ", -1);
                    String ReportID = parts[0];              
                    String Date = parts[1];
                    String Status = parts[4];
                    model.addRow(new Object[]{ReportID,Date,Status});
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }                                 

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if(selectedValue == null){
            JOptionPane.showMessageDialog(this,"Please select a row first.");
            return;
        }
        String ReportID = selectedValue.toString();
        JFrame ReportFrame = new JFrame("Report details");
        ReportFrame.setSize(400,300);
        JLabel lblReportID = new JLabel("ReportID:");
        JLabel lblDate = new JLabel("Date:");
        JLabel lblAT = new JLabel("Assessment:");
        JLabel lblStudentID = new JLabel("Student ID:");
        JLabel lblStatus = new JLabel("Status:");
        JLabel lblSupID = new JLabel("Supervisor ID:");
        JLabel lblSecID = new JLabel("Second Marker ID:");
        String[] ReportData = fnc.readSingleLine("Report.txt",ReportID);
        System.out.println(Arrays.toString(ReportData));
        if(ReportData == null || ReportData.length != 7){
            JLabel lblError = new JLabel("Error: Invalid report ID data format.");
            ReportFrame.add(lblError);
        }else{
            JLabel lblReportValue = new JLabel(ReportData[0]);
            JLabel lblDateValue = new JLabel(ReportData[1]);
            JLabel lblATValue = new JLabel(ReportData[2]);
            JLabel lblStudentValue = new JLabel(ReportData[3]);
            JLabel lblStatusValue = new JLabel(ReportData[4]);
            JLabel lblSupValue = new JLabel(ReportData[5]);
            JLabel lblSecValue = new JLabel(ReportData[6]);
            
            ReportFrame.setLayout(null);
            lblReportID.setBounds(20, 20, 80, 20);
            lblReportValue.setBounds(130, 20, 150, 20);
            lblDate.setBounds(20, 50, 80, 20);
            lblDateValue.setBounds(130, 50, 150, 20);
            lblAT.setBounds(20, 80, 80, 20);
            lblATValue.setBounds(130, 80, 150, 20);
            lblStudentID.setBounds(20, 110, 80, 20);
            lblStudentValue.setBounds(130, 110, 250, 20); 
            lblStatus.setBounds(20, 140, 150, 20);
            lblStatusValue.setBounds(130, 140, 250, 20);
            lblSupID.setBounds(20, 170, 250, 20);
            lblSupValue.setBounds(130, 170, 150, 20);
            lblSecID.setBounds(20, 200, 250, 20);
            lblSecValue.setBounds(130, 200, 150, 20);
            
            ReportFrame.add(lblReportID);
            ReportFrame.add(lblReportValue);
            ReportFrame.add(lblDate);
            ReportFrame.add(lblDateValue);
            ReportFrame.add(lblAT);
            ReportFrame.add(lblATValue);
            ReportFrame.add(lblStudentID);
            ReportFrame.add(lblStudentValue);
            ReportFrame.add(lblStatus);
            ReportFrame.add(lblStatusValue);
            ReportFrame.add(lblSupID);
            ReportFrame.add(lblSupValue);
            ReportFrame.add(lblSecID);
            ReportFrame.add(lblSecValue);
        }
        ReportFrame.setLocationRelativeTo(null);
        ReportFrame.setVisible(true);
        ReportFrame.setAlwaysOnTop(true);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReport;
    // End of variables declaration                   
}
