/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student;

/**
 *
 * @author user
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Student_UI extends javax.swing.JFrame {
    Student student = new Student("TP34567","stud1","APU2F2402CS(AI)");

    String filePath = "C:\\Users\\user\\Desktop\\JAVA Assignment\\Report.txt" ;
    String AssessmentFile = "C:\\Users\\user\\Desktop\\JAVA Assignment\\AssessmentType.txt" ;
    String RemarkFile = "C:\\Users\\user\\Desktop\\JAVA Assignment\\Remark.txt";
    String PreDateFile ="C:\\Users\\user\\Desktop\\JAVA Assignment\\Presentation Request.txt";
        File file =new File(filePath);
        File Afile = new File(AssessmentFile);
        File Rfile = new File(RemarkFile);
        File Pfile = new File(PreDateFile);

    
    

    /**
     * Creates new form Student_UI
     */
    public Student_UI() {
        initComponents();
         ConfirmEditBtn.setVisible(false);
        String StudentId =student.getTpNumber(); 
        StudentIDTxt.setText(StudentId);
        String IntakeCode =student.getIntake();
        IntakeCodeTxt.setText(IntakeCode);
        DefaultTableModel model = (DefaultTableModel)AssessmentTable.getModel();
        AssessmentTable.setDefaultEditor(Object.class, null);
        RemarkTable.setDefaultEditor(Object.class, null);
        try {
            BufferedReader br = new BufferedReader(new FileReader(Afile));
            br.readLine();
            
            Object[] tableLines = br.lines().toArray();
            
            
            for(int i =0; i<tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow  = line.split("@");
                for (int j = 0; j < dataRow.length; j++) {
                   dataRow[j] = dataRow[j].trim();
            
                }
                if (dataRow[0].equals(student.getTpNumber())){
                    
                    Object[] rowData = {dataRow[2],"Pending"};
                    model.addRow(rowData);
                    AssessmentTypeComboBox.addItem(dataRow[2]);
                    AssessmentForPresentDate.addItem(dataRow[2]);
                    
                } else if (dataRow[1].equals(student.getIntake())){
                    
                   Object[] rowData = {dataRow[2],"Pending"};
                    model.addRow(rowData);
                    AssessmentTypeComboBox.addItem(dataRow[2]);
                    AssessmentForPresentDate.addItem(dataRow[2]);
                }
                
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            br.readLine();
            Object[] tableLines = br.lines().toArray();
            
            for(int i =0; i<tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow  = line.split("@");
                for (int j = 0; j < dataRow.length; j++) {
                   dataRow[j] = dataRow[j].trim();
            
                }
                for(int counter =0; counter<model.getRowCount(); counter++ ){
                    if (dataRow[3].equals(student.getTpNumber()) && dataRow[2].equals(model.getValueAt(counter, 0))){
                        model.setValueAt("Submitted", counter, 1);
                } 
                
                }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AssessmentTable = new javax.swing.JTable();
        StudentID = new javax.swing.JLabel();
        SumbitLinkTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        RequestPreDateBtn = new javax.swing.JButton();
        StudentIDTxt = new javax.swing.JLabel();
        AssessmentTypeComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        AssessmentForPresentDate = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        IntakeCodeTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PresentationDateTxt = new javax.swing.JLabel();
        EditBtn = new javax.swing.JButton();
        ConfirmEditBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        RemarkTable = new javax.swing.JTable();
        CheckResultBtn = new javax.swing.JButton();
        SelectedLine = new javax.swing.JLabel();
        Status_Pdate = new javax.swing.JLabel();
        Status_Predate = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AssessmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AssessmentType", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AssessmentTable);

        StudentID.setText("Student ID:");

        jLabel1.setText("Submit Link :");

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        RequestPreDateBtn.setText("Request Presentation Date");
        RequestPreDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestPreDateBtnActionPerformed(evt);
            }
        });

        StudentIDTxt.setText("StudentIDTxt");

        jLabel2.setText("Assessment You want to submit/delete :");

        jLabel3.setText("Assesment Selected :");

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Intake Code:");

        IntakeCodeTxt.setText("IntakeCodeTxt");

        jLabel5.setText("Presentation Date:");

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        ConfirmEditBtn.setText("Confirm Edit");
        ConfirmEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmEditBtnActionPerformed(evt);
            }
        });

        RemarkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Name", "Feedback 1", "Feedback 2", "Result"
            }
        ));
        jScrollPane3.setViewportView(RemarkTable);

        CheckResultBtn.setText("Check Feedback and Result");
        CheckResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckResultBtnActionPerformed(evt);
            }
        });

        Status_Predate.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(148, 148, 148))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SumbitLinkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(SubmitBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(DeleteBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(EditBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ConfirmEditBtn))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AssessmentForPresentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CheckResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RequestPreDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(PresentationDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addComponent(Status_Pdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(Status_Predate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(11, 11, 11)
                                    .addComponent(AssessmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectedLine)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(IntakeCodeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentID)
                    .addComponent(StudentIDTxt)
                    .addComponent(SelectedLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IntakeCodeTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssessmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumbitLinkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBtn)
                    .addComponent(DeleteBtn)
                    .addComponent(EditBtn)
                    .addComponent(ConfirmEditBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssessmentForPresentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(RequestPreDateBtn)
                    .addComponent(jLabel5)
                    .addComponent(PresentationDateTxt)
                    .addComponent(Status_Pdate)
                    .addComponent(Status_Predate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckResultBtn)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RequestPreDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestPreDateBtnActionPerformed
        // TODO add your handling code here:
        String AssessmentSelected = (String) AssessmentForPresentDate.getSelectedItem();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            br.readLine();
            Object[] tableLines = br.lines().toArray();
            
            
            for(int i =0; i<tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow  = line.split("@");
                for (int j = 0; j < dataRow.length; j++) {
                   dataRow[j] = dataRow[j].trim();
            
                }
                if (dataRow[2].equals(AssessmentSelected) && dataRow[3].equals(student.getTpNumber())){
                    Project project = new Project(dataRow[0],dataRow[1],dataRow[2],dataRow[3],dataRow[4],"","");
                    try {
            BufferedReader br1 = new BufferedReader(new FileReader(Pfile));
            br1.readLine();
            Object[] tableLines1 = br1.lines().toArray();
            
            
            for(int k =0; k<tableLines1.length; k++)
            {
                String line1 = tableLines1[k].toString().trim();
                String[] dataRow1  = line1.split("@");
                for (int m = 0; m < dataRow1.length; m++) {
                   dataRow1[m] = dataRow1[m].trim();
                }
                System.out.println(Arrays.toString(dataRow1));
                if (dataRow1[0].equals(project.getReportID())){ 
                    PresentationDateTxt.setText(dataRow1[1]);
                    Status_Predate.setText(dataRow1[2]);
                } 
                
            }
        
        } 
        catch (Exception ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }

                }else{
                    Status_Predate.setText("No report submitted");
                }    
            }
            
        
        } 
        catch (Exception ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RequestPreDateBtnActionPerformed

    
    
    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        
        int maxId = 0;
        String submitLink = SumbitLinkTxt.getText();
        String selectedAssessment = (String) AssessmentTypeComboBox.getSelectedItem();
        if(submitLink.isEmpty() || selectedAssessment == null){
            System.out.println("Please provide a submission link and select an assessment type.");
            } else{
            
            
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            reader.readLine();    
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("@");
                if (parts.length > 0) {
                    String reportId = parts[0];
                    if (reportId.startsWith("R")) {
                        int currentId = Integer.parseInt(reportId.substring(1).trim());
                        if (currentId > maxId) {
                            maxId = currentId;
                        }
                    }
                }
            }
            reader.close();
        }   catch (FileNotFoundException ex) {
                Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) { 
                Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
            }

        // Increment the maximum ID found
        int nextId = maxId + 1;
        String newReportId = String.format("R%02d", nextId);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();
        String CurrentDateTime = dtf.format(now);
        Project project = new Project(newReportId,CurrentDateTime,selectedAssessment,student.getTpNumber(),"Pending","","");
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true))) {
            String[] dataRow ={newReportId,CurrentDateTime,selectedAssessment,student.getTpNumber(),"Pending","-","-"};
            writer.write(String.join(" @ ", dataRow));
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(Rfile, true))) {
            String[] dataRow ={newReportId,"","","","","",submitLink};
            writer.write(String.join(" @ ", dataRow));
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(Pfile, true))) {
            String[] dataRow ={newReportId,"","Pending"};
            writer.write(String.join(" @ ", dataRow));
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel)AssessmentTable.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
    if (selectedAssessment.equals(model.getValueAt(i, 0))) {
        model.setValueAt("Submitted", i, 1);
    }
    }
    }
    
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        String selectedAssessment = (String) AssessmentTypeComboBox.getSelectedItem();
        List<String[]> lines = new ArrayList<>();
        String ReportId = getReportId(selectedAssessment);
         try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
             reader.readLine();
             String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line.split(" @ "));
            } 
         }catch (IOException e) {
            e.printStackTrace();
        }
        boolean found = false;       
        for (int i = 0; i < lines.size(); i++) {
            String[] line = lines.get(i);
            if (line[0].equals(ReportId)) { // Adjust condition based on your identifier
                found = true;               
                lines.remove(i);
                SelectedLine.setText(String.valueOf(i));
            }
           }
        // If the StudentId and ProjectName are not found, print a message
        if (!found) {
            JOptionPane.showMessageDialog(null, "You cannot delete report that you haven't submitted.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
             writer.write("ReportID , Date , AssessmentType , StudentID , Status , SupervisorID , SecondMarkerID");
             writer.newLine();
            for (String[] lineTest : lines) {
                writer.write(String.join(" @ ", lineTest));
                writer.newLine();
            }
        } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            List<String[]> Rlines = new ArrayList<>();
            try (BufferedReader reader = new BufferedReader(new FileReader(Rfile))) {
             reader.readLine();
             String Rline;
            while ((Rline = reader.readLine()) != null) {
                Rlines.add(Rline.split(" @ "));   
            }  Rlines.remove(Integer.parseInt(SelectedLine.getText()));
            }catch (IOException e) {
            e.printStackTrace();
            }
        
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(Rfile))) {
             writer.write("ReportID , Feedback , Feedback2, Result1, Result2, Result, Submit Link");
             writer.newLine();
            for (String[] Rline : Rlines) {
                writer.write(String.join(" @ ", Rline));
                writer.newLine();
            }
            } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            /*delete in Pfile*/
            List<String[]> Plines = new ArrayList<>();
            try (BufferedReader reader = new BufferedReader(new FileReader(Pfile))) {
             reader.readLine();
             String Pline;
            while ((Pline = reader.readLine()) != null) {
                Plines.add(Pline.split(" @ "));                
            }Plines.remove(Integer.parseInt(SelectedLine.getText())); 
            }catch (IOException e) {
            e.printStackTrace();
            }
        
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(Pfile))) {
             writer.write("ReportId , Present Date , Status");
             writer.newLine();
            for (String[] Pline : Plines) {
                writer.write(String.join(" @ ", Pline));
                writer.newLine();
            }
            } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
            }
               
            


                
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private String getReportId(String selectedAssessment){
        List<String[]> lines = new ArrayList<>();
         try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
             reader.readLine();
             String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line.split(" @ "));
                
            } 
         }catch (IOException e) {
            e.printStackTrace();
        }
       
        for (int i = 0; i < lines.size(); i++) {
            String[] line = lines.get(i);
            if (line[2].equals(selectedAssessment) && line[3].equals(student.getTpNumber())) { // Adjust condition based on your identifier
                
                Project project = new Project(line[0],line[1],line[2],line[3],line[4],"-","-");
                return project.getReportID();
            }
            
            
    }
        return null;
    }
    
    
    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        String selectedAssessment = (String) AssessmentTypeComboBox.getSelectedItem();
        ConfirmEditBtn.setVisible(true);
        SubmitBtn.setVisible(false);
        DeleteBtn.setVisible(false);        
        String ProjectId = getReportId(selectedAssessment);
        System.out.println(ProjectId);
        List<String[]> lines = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(Rfile))) {
            reader.readLine();
            String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line.split(" @ "));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }

        boolean found = false;

        // Iterate over the list of lines
        for (int i = 0; i < lines.size(); i++) {
            String[] parts = lines.get(i);
            System.out.println(Arrays.toString(parts));
            // Check if the line contains the specific StudentId and ProjectName
            if (parts[0].equals(ProjectId)) {
                // Update the Status to the new status
                SumbitLinkTxt.setText(parts[6]);
                found = true;
                break;
            }
        }

        // If the StudentId and ProjectName are not found, print a message
        if (!found) {
            System.out.println("StudentId and ProjectName not found");
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    private void ConfirmEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmEditBtnActionPerformed
        // TODO add your handling code here:
        String SubmitLink = SumbitLinkTxt.getText();
        String selectedAssessment = (String) AssessmentTypeComboBox.getSelectedItem();
        List<String[]> lines = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(Rfile))) {
            reader.readLine();
            String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line.split(" @ "));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Iterate over the list of lines
        for (int i = 0; i < lines.size(); i++) {
            String[] parts = lines.get(i);

            // Check if the line contains the specific StudentId and ProjectName
            if (parts[0].equals(getReportId(selectedAssessment))) {
                // Update the Status to the new status
                parts[6] = SubmitLink;
                break;
            }
        }
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(Rfile))) {
             writer.write("ReportID , Feedback , Feedback2, Result1, Result2, Result, Submit Link");
             writer.newLine();
            for (String[] line : lines) {
                writer.write(String.join(" @ ", line));
                writer.newLine();
            }
        } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        SubmitBtn.setVisible(true);
        DeleteBtn.setVisible(true);
        SumbitLinkTxt.setText("");
    }//GEN-LAST:event_ConfirmEditBtnActionPerformed

    private void CheckResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckResultBtnActionPerformed
        // TODO add your handling code here:
        boolean found = false;
        String selectedAssessment = (String) AssessmentForPresentDate.getSelectedItem();
        List<String[]> lines = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel)RemarkTable.getModel();
        try (BufferedReader reader = new BufferedReader(new FileReader(Rfile))) {
            reader.readLine();
            String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line.split(" @ "));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Student_UI.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Iterate over the list of lines
        for (int i = 0; i < lines.size(); i++) {
            String[] parts = lines.get(i);

            // Check if the line contains the specific StudentId and ProjectName
            if (parts[0].equals(getReportId(selectedAssessment))) {
                // Update the Status to the new status
                String[] row = {selectedAssessment,parts[1],parts[2],parts[5]};
                model.removeRow(0);
                model.addRow(row);
                found = true;
            }  
            }
        if(!found){
             JOptionPane.showMessageDialog(null, "The selected report has not been submitted.", "Error", JOptionPane.ERROR_MESSAGE);   
            }
        
    }//GEN-LAST:event_CheckResultBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AssessmentForPresentDate;
    private javax.swing.JTable AssessmentTable;
    private javax.swing.JComboBox<String> AssessmentTypeComboBox;
    private javax.swing.JButton CheckResultBtn;
    private javax.swing.JButton ConfirmEditBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JLabel IntakeCodeTxt;
    private javax.swing.JLabel PresentationDateTxt;
    private javax.swing.JTable RemarkTable;
    private javax.swing.JButton RequestPreDateBtn;
    private javax.swing.JLabel SelectedLine;
    private javax.swing.JLabel Status_Pdate;
    private javax.swing.JLabel Status_Predate;
    private javax.swing.JLabel StudentID;
    private javax.swing.JLabel StudentIDTxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField SumbitLinkTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
