/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author user
 */
public class StudentMain extends javax.swing.JFrame {
    Student student = new Student("TP34567","stud1","APU2F2402CS(AI)");
    private int SelectedLine;
    String reportFile = "Report.txt";
    FileUtil f = new FileUtil();
    File file = new File(f.getFileLocation(reportFile));

    /**
     * Creates new form StudentMain
     */
    public StudentMain() {
        initComponents();
        studentTpTxt.setText(student.getTpNumber());
            
    }
    
    public void setSelectedLine(int SelectedLine){
        this.SelectedLine = SelectedLine;
    }
    
    public int getSelectedLine(){
        return SelectedLine;
    }
    
    public String getReportId(String selectedAssessment,String TpNumber){
        List<String[]> lines = new ArrayList<>();
         try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
             reader.readLine();
             String line;
            while ((line = reader.readLine()) != null) {
                lines.add(line.split(" @ "));
                
            } 
         }catch (IOException e) {
            e.printStackTrace();
        }
       
        for (int i = 0; i < lines.size(); i++) {
            String[] line = lines.get(i);
            if (line[2].equals(selectedAssessment) && line[3].equals(TpNumber)) { // Adjust condition based on your identifier
                
                Project project = new Project(line[0],line[1],line[2],line[3],line[4],"-","-");
                return project.getReportID();
            }
            
            
    }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SubmitReportBtn = new javax.swing.JButton();
        RequestDateBtn = new javax.swing.JButton();
        CheckResultBtn = new javax.swing.JButton();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Student Homepage");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TP Number:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("StudentTPNumber");

        SubmitReportBtn.setText("Submit Report");
        SubmitReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitReportBtnActionPerformed(evt);
            }
        });

        RequestDateBtn.setText("Request Presentation Date");
        RequestDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestDateBtnActionPerformed(evt);
            }
        });

        CheckResultBtn.setText("Check Submission Result/Status");
        CheckResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckResultBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(SubmitReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RequestDateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(RequestDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitReportBtnActionPerformed
        // TODO add your handling code here:
        SubmitReport submitReport = new SubmitReport(student.getTpNumber(),student.getIntake());
        submitReport.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitReportBtnActionPerformed

    private void RequestDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestDateBtnActionPerformed
        // TODO add your handling code here:
        RequestPresentationDate requestPresentationDate = new RequestPresentationDate(student.getTpNumber(),student.getIntake());
        requestPresentationDate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RequestDateBtnActionPerformed

    private void CheckResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckResultBtnActionPerformed
        // TODO add your handling code here:
        CheckFeedbackResult checkFeedbackResult = new CheckFeedbackResult(student.getTpNumber(),student.getIntake());
        checkFeedbackResult.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CheckResultBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckResultBtn;
    private javax.swing.JButton RequestDateBtn;
    private javax.swing.JButton SubmitReportBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
